#!/bin/bash
#       This program is free software; you can redistribute it and/or modify
#       it under the terms of the GNU General Public License as published by
#       the Free Software Foundation; either version 2 of the License, or
#       (at your option) any later version.
#       
#       This program is distributed in the hope that it will be useful,
#       but WITHOUT ANY WARRANTY; without even the implied warranty of
#       MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#       GNU General Public License for more details.
#       
#       You should have received a copy of the GNU General Public License
#       along with this program; if not, write to the Free Software
#       Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#       MA 02110-1301, USA.
#		created by	:ibnu yahya <ibnu.yahya@toroo.org>
#				 indira cempakasari <indira@toroo.org>
#		modify by	:<nama><email>

APPNAME="" #nama paket
VERSION="" #versi paket
ALIAS="" #nama
EXTENSION="tar.bz2" #extensi source bisa di ganti
TMP="/tmp"	
SOURCEDIR="$TMP/$APPNAME-$VERSION"
DESTDIR="$TMP/$APPNAME-$VERSION-binary"

ARC=`uname -m`

if [ $ARC == i486 ]
then
     SLKCFLAGS="-O2 -march=i486 -mtune=i686"
     LIBDIR="/usr/lib"
elif [ $ARC == i686 ]
then
     SLKCFLAGS="-O2 -march=i686 -mtune=i686"
     LIBDIR="/usr/lib"
elif [ $ARC == x86_64 ]
then
     SLKCFLAGS="-O2 -fPIC"
     LIBDIR="/usr/lib64"
else
     SLKCFLAGS="-O2"
     LIBDIR=""
fi 

mkdir -p $TMP/$APPNAME-$VERSION
mkdir -p $TMP/$APPNAME-$VERSION-binary

tar vxf $APPNAME-$VERSION.$EXTENSION -C $SOURCEDIR

cd $SOURCEDIR/$APPNAME-$VERSION
mkdir -p build
cd build
cmake \
    -DCMAKE_C_FLAGS:STRING="$SLKCFLAGS" \
    -DCMAKE_CXX_FLAGS:STRING="$SLKCFLAGS" \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DLIB_SUFFIX=$LIBDIR \
    -DMAN_INSTALL_DIR=/usr/man \
    -DCMAKE_BUILD_TYPE=Release ..
make
make install DESTDIR=$DESTDIR

cd $DESTDIR
/sbin/makepkg -l y -c n $TMP/$APPNAME-$VERSION-$ARC-$ALIAS-toroo.tlz
md5sum $TMP/$APPNAME-$VERSION-$ARC-$ALIAS-toroo.tlz > $TMP/$APPNAME-$VERSION-$ARC-$ALIAS-toroo.md5
requiredbuilder -z $TMP/$APPNAME-$VERSION-$ARC-$ALIAS-toroo.tlz > $TMP/$APPNAME-$VERSION-$ARC-$ALIAS-toroo.dep
